cms_api/api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    # path('api/graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
    # 忽略csrf_token验证
    path('api/graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    path('system/', include('f01_system.f01_urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home.index import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

zxkj/f06_contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('recruit/', views.recruit, name='recruit'),
]

zxkj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .f01_index import views
from . import settings

urlpatterns = [

    path('', views.index, name='index'),
    path('profile/', include('zxkj.f02_profile.urls', namespace='profile')),   # 公司简介
    path('news/', include('zxkj.f03_news.urls', namespace='news')),   # 新闻动态
    path('product/', include('zxkj.f04_product.urls', namespace='product')),   # 产品中心
    path('science/', include('zxkj.f05_science.urls', namespace='science')),   # 科研基地
    path('contact/', include('zxkj.f06_contact.urls', namespace='contact')),   # 联系我们
    path('service/', include('zxkj.f08_service.urls', namespace='service')),   # 服务支持
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zxkj/f03_news/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

class News(models.Model):
    """添加新闻模块"""
    NEWS_TYPE = (
        ('企业要闻', '企业要闻'),
        ('行业新闻', '行业新闻'),
        ('通知公告', '通知公告'),
    )
    title = models.CharField(max_length=50, verbose_name='标题')
    description = RichTextField(default='', verbose_name='内容')
    # description = UEditorField(u'内容', default='', width=950, height=280, imagePath='news/images/', filePath='news/files/')
    news_type = models.CharField(choices=NEWS_TYPE, max_length=50, verbose_name='新闻类型')
    photo = models.ImageField(upload_to='news/', blank=True, null=True, verbose_name="图片")
    publish_date = models.DateTimeField(max_length=20, default=timezone.now, verbose_name='发布时间')
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    sort = models.CharField(max_length=100, verbose_name='排序')
    state = models.CharField(max_length=100, default="1",verbose_name='状态') # 默认1 有效
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '新闻'
        verbose_name_plural = '新闻列表'
        ordering = ['-publish_date']

templates/f07_contact/f01_contact.html
{% extends "../f01_common/f01_base.html" %}
{% load static %}
{% block title %}联系我们{% endblock %}
{% block content %}
<!-- 广告横幅 -->
<div class="container-fluid">
  <div class="row ">
    <img class="img-responsive model-img" src="{% static 'img/contact.jpg' %}">
  </div>
</div>
<!--主体内容-->
<div class="container">
  <div class="row row-3">
    <!--侧边栏-->
    <div class="col-md-3">
      <div class="model-title">
        人才招聘
      </div>
      <div class="model-list">
        <ul class="list-group">
          <li class="list-group-item" id="contact">
            <a class="link-color" href="{% url 'contact:contact' %}">联系我们</a>
          </li>
          <li class="list-group-item" id="recruit">
            <a href="{% url 'contact:recruit' %}">加入恒达</a>
          </li>
        </ul>
      </div>
    </div>
    <!--文字和图片-->
    <div class="col-md-9">
      <div class="model-details-title">
        欢迎咨询
      </div>
      <div class="row">
        <!--信息-->
        <div class="col-md-4">
          <div class="contact-left">
            <h2>恒达科技有限公司</h2>
            <span>HengDa Science and Technology</span>
            <ul>
              <li><span>业务咨询一：</span>111-111111</li>
              <li><span>业务咨询二：</span>222-222222</li>
              <li><span>咨询电话：</span>0111-111111111</li>
              <li><span>企业传真：</span>0222-222222222</li>
              <li><span>地址：</span>广东省深圳市南山街道408</li>
              <li><span>邮编：</span>567389</li>
              <li><span>网址：</span><a href="http://tianxiao.work">http://tianxiao.work</a></li>
            </ul>
          </div>
        </div>
        <!--图片-->
        <div class="col-md-8" style="margin-top: 20px;">


          <!DOCTYPE html
            PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
          <html xmlns="http://www.w3.org/1999/xhtml">

          <head>
            <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
            <meta name="keywords" content="百度地图,百度地图API，百度地图自定义工具，百度地图所见即所得工具" />
            <meta name="description" content="百度地图API自定义地图，帮助用户在可视化操作下生成百度地图" />
            <title>百度地图API自定义地图</title>
            <!--引用百度地图API-->
            <style type="text/css">
              html,
              body {
                margin: 0;
                padding: 0;
              }

              .iw_poi_title {
                color: #CC5522;
                font-size: 14px;
                font-weight: bold;
                overflow: hidden;
                padding-right: 13px;
                white-space: nowrap
              }

              .iw_poi_content {
                font: 12px arial, sans-serif;
                overflow: visible;
                padding-top: 4px;
                white-space: -moz-pre-wrap;
                word-wrap: break-word
              }
            </style>
            <script type="text/javascript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true"></script>
          </head>

          <body>
            <!--百度地图容器-->
            <div style="width:500px;height:450px;border:#ccc solid 1px;" id="dituContent"></div>
          </body>
          <script type="text/javascript">
            //创建和初始化地图函数：
            function initMap() {
              createMap();//创建地图
              setMapEvent();//设置地图事件
              addMapControl();//向地图添加控件
              addMarker();//向地图中添加marker
            }

            //创建地图函数：
            function createMap() {
              var map = new BMap.Map("dituContent");//在百度地图容器中创建一个地图
              var point = new BMap.Point(114.123939, 22.561723);//定义一个中心点坐标
              map.centerAndZoom(point, 17);//设定地图的中心点和坐标并将地图显示在地图容器中
              window.map = map;//将map变量存储在全局
            }

            //地图事件设置函数：
            function setMapEvent() {
              map.enableDragging();//启用地图拖拽事件，默认启用(可不写)
              map.enableScrollWheelZoom();//启用地图滚轮放大缩小
              map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)
              map.enableKeyboard();//启用键盘上下左右键移动地图
            }

            //地图控件添加函数：
            function addMapControl() {
              //向地图中添加缩放控件
              var ctrl_nav = new BMap.NavigationControl({
                anchor: BMAP_ANCHOR_TOP_LEFT,
                type: BMAP_NAVIGATION_CONTROL_LARGE
              });
              map.addControl(ctrl_nav);
              //向地图中添加缩略图控件
              var ctrl_ove = new BMap.OverviewMapControl({
                anchor: BMAP_ANCHOR_BOTTOM_RIGHT,
                isOpen: 1
              });
              map.addControl(ctrl_ove);
              //向地图中添加比例尺控件
              var ctrl_sca = new BMap.ScaleControl({ anchor: BMAP_ANCHOR_BOTTOM_LEFT });
              map.addControl(ctrl_sca);
            }

            //标注点数组
            var markerArr = [{
              title: "恒达科技有限公司",
              content: "虚假标记，只为学习",
              point: "114.123517|22.561106",
              isOpen: 0,
              icon: { w: 21, h: 21, l: 0, t: 0, x: 6, lb: 5 }
            }
            ];

            //创建marker
            function addMarker() {
              for (var i = 0; i < markerArr.length; i++) {
                var json = markerArr[i];
                var p0 = json.point.split("|")[0];
                var p1 = json.point.split("|")[1];
                var point = new BMap.Point(p0, p1);
                var iconImg = createIcon(json.icon);
                var marker = new BMap.Marker(point, { icon: iconImg });
                var iw = createInfoWindow(i);
                var label = new BMap.Label(json.title, { "offset": new BMap.Size(json.icon.lb - json.icon.x + 10, -20) });
                marker.setLabel(label);
                map.addOverlay(marker);
                label.setStyle({
                  borderColor: "#808080",
                  color: "#333",
                  cursor: "pointer"
                });

                (function () {
                  var index = i;
                  var _iw = createInfoWindow(i);
                  var _marker = marker;
                  _marker.addEventListener("click", function () {
                    this.openInfoWindow(_iw);
                  });
                  _iw.addEventListener("open", function () {
                    _marker.getLabel().hide();
                  })
                  _iw.addEventListener("close", function () {
                    _marker.getLabel().show();
                  })
                  label.addEventListener("click", function () {
                    _marker.openInfoWindow(_iw);
                  })
                  if (!!json.isOpen) {
                    label.hide();
                    _marker.openInfoWindow(_iw);
                  }
                })()
              }
            }

            //创建InfoWindow
            function createInfoWindow(i) {
              var json = markerArr[i];
              var iw = new BMap.InfoWindow("<b class='iw_poi_title' title='" + json.title + "'>" + json.title + "</b><div class='iw_poi_content'>" + json.content + "</div>");
              return iw;
            }

            //创建一个Icon
            function createIcon(json) {
              var icon = new BMap.Icon("https://img.imgdb.cn/item/606dcabb8322e6675c45b1b9.jpg", new BMap.Size(json.w, json.h), {
                imageOffset: new BMap.Size(-json.l, -json.t),
                infoWindowOffset: new BMap.Size(json.lb + 5, 1),
                offset: new BMap.Size(json.x, json.h)
              })
              return icon;
            }

            initMap();//创建和初始化地图
          </script>

          </html>


        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/f07_contact/f02_recruit.html
{% extends "../f01_common/f01_base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}加入我们{% endblock %}
{% block content %}
<script src="{% static 'layDate-v5.2.0/laydate/laydate.js' %}"></script>

<!-- 广告横幅 -->
<div class="container-fluid">
  <div class="row">
    <img class="img-responsive model-img" src="{% static 'img/contact.jpg' %}">
  </div>
</div>
<!-- 主体内容 -->
<div class="container">
  <div class="row row-3">
    <!-- 侧边导航栏 -->
    <div class="col-md-3">
      <div class="model-title">
        人才招聘
      </div>
      <div class="model-list">
        <ul class="list-group">
          <li class="list-group-item" id="contact">
            <a href="{% url 'contact:contact' %}">联系我们</a>
          </li>
          <li class="list-group-item" id="recruit">
            <a href="{% url 'contact:recruit' %}">加入恒达</a>
          </li>
        </ul>
      </div>
    </div>
    <!-- 说明文字和图片 -->
    <div class="col-md-9">
      <div class="model-details-title">
        加入恒达
      </div>
      <div class="model-details">
        <div class="panel-group" id="accordion">
          {% for ad in AdList %}
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="panel{{ ad.id }}">
              <h4 class="panel-title">
                {% if forloop.first %}
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ ad.id }}">
                  {% else %}
                  <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ ad.id }}">
                    {% endif %}
                    {{ ad.title }}
                  </a>
              </h4>
            </div>
            {% if forloop.first %}
            <div id="collapse{{ ad.id }}" class="panel-collapse collapse in">
              {% else %}
              <div id="collapse{{ ad.id }}" class="panel-collapse collapse">
                {% endif %}
                <div class="panel-body">
                  <p>{{ ad.description }}</p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            请填写个人简历
          </div>
          <div class="panel-body">
            <div class="row">
              <form action="." name="resumeForm" method="post" class="form-horizontal" role="form"
                enctype="multipart/form-data">
                {% csrf_token %}
                <!-- 左侧 -->
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="col-sm-3 control-label">姓名：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.name|add_class:"form-control"|attr:"placeholder=请填写姓名" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">身份证号：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.personID|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">性别：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.sex|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">出生日期：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.birth|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">邮箱：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.email|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">学历：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.edu|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">毕业学校：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.school|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">专业：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.major|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">申请职位：</label>
                    <div class="col-sm-9">
                      {{ resumeForm.position|add_class:"form-control" }}
                    </div>
                  </div>
                </div>
                <!-- 右侧 -->
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="col-sm-12" style="text-align:center">
                      <img id="profileshow" src="{% static 'img/sample.png' %}" style="width:120px">
                    </div>
                    <label class="col-sm-5 control-label">上传证件照片：</label>
                    {{ resumeForm.photo }}
                  </div>
                  <div class="form-group">
                    <label class="col-sm-12 control-label">学习或工作经历：</label>
                    <div class="col-sm-12">
                      {{ resumeForm.experience|add_class:"form-control" }}
                    </div>
                  </div>
                </div>
                <div class="col-md-12">
                  <center><input type="submit" class="btn btn-primary" onclick="myFunction()" value="提交" /></center>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
  <script>
    function myFunction() {
      alert("简历信息已成功上传，初试结果近期会以邮件方式发送至您的邮箱。");
    }
  </script>

  <script>
    laydate.render({
      elem: '#id_birth'
    });
  </script>
  <script>
    $(function () {
      $('#id_photo').on('change', function () {
        var r = new FileReader();
        f = document.getElementById('id_photo').files[0];
        r.readAsDataURL(f);
        r.onload = function (e) {
          document.getElementById('profileshow').src = this.result;
        };
      });
    });
  </script>
</div>
{% endblock %}

templates/f07_contact/f03_recruit_success.html
{% extends "../f01_common/f01_base.html" %}
{% load static %}
{% block title %}加入我们{% endblock %}
{% block content %}
<!-- 主体内容 -->
<div class="container">
  <div class="row">
    <div class="alert alert-success">
      <strong>成功!</strong> 简历信息已成功上传，初试结果近期会以邮件方式发送至您的邮箱。
    </div>
  </div>
</div>
{% endblock %}