cms_api/api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    # path('api/graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
    # 忽略csrf_token验证
    path('api/graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    path('system/', include('f01_system.f01_urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home.index import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

zxkj/f02_profile/urls.py
from django.urls import path
from zxkj.f02_profile import views

app_name = 'profile'
urlpatterns = [
    path('', views.index, name='index'),
    path('honor/', views.honor, name='honor'),
]

zxkj/f03_news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('<str:news_type>/', views.news, name='list'),
    path('detail/<int:id>/', views.details, name='detail'),
]

zxkj/f04_product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.list, name='list'),
    path('<str:product_type_name>/', views.list, name='list'),
    path('details/<int:id>/', views.details, name="details"),
    path('type', views.types_list, name="type"),
]

zxkj/f06_contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('recruit/', views.recruit, name='recruit'),
]

zxkj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .f01_index import views
from . import settings

urlpatterns = [

    path('', views.index, name='index'),
    path('profile/', include('zxkj.f02_profile.urls', namespace='profile')),   # 公司简介
    path('news/', include('zxkj.f03_news.urls', namespace='news')),   # 新闻动态
    path('product/', include('zxkj.f04_product.urls', namespace='product')),   # 产品中心
    path('science/', include('zxkj.f05_science.urls', namespace='science')),   # 科研基地
    path('contact/', include('zxkj.f06_contact.urls', namespace='contact')),   # 联系我们
    path('service/', include('zxkj.f08_service.urls', namespace='service')),   # 服务支持
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/f01_common/f01_base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<!-- head -->
{% include "./f02_head.html" %}

<body>
  <!-- navbar -->
  {% include "./f03_navbar.html" %}
  <!-- content -->
  {% block content %}{% endblock %}
  <!-- footer -->
  {% include "./f04_footer.html" %}
</body>
<script>
  $(function () {
    $(".dropdown").mouseover(function () {
      $(this).addClass("open")
    });
    $(".dropdown").mouseleave(function () {
      $(this).removeClass("open");
    });
    $('#{{active_menu}}').addClass("active");
    $('#{{sub_menu}}').addClass("active");
  });
</script>

</html>

templates/f01_common/f02_head.html
{% load static %}

<head>
  <meta charset="UTF-8" http-equiv="Content-Type">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="icon" sizes="any" mask="" href="{% static 'favicon.svg' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href="{% static 'products.css' %}" rel="stylesheet">
  <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
  <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
  <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>

templates/f01_common/f03_navbar.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<!-- 导航条 -->
<nav class="navbar navbar-default" role="navigation" id="vue-app">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example"
        aria-expanded="false">
        <span>导航条</span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example">
      <ul class="nav navbar-nav">
        <li class="nav-top">
          <a href="/">首页</a>
        </li>
        <li class="dropdown nav-top">
          <a href="#" class="dropdown-toggle on" data-toggle="dropdown">公司简介</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'profile:index' %}">企业概况</a></li>
            <li><a href="{% url 'profile:honor' %}">荣誉资质</a></li>
          </ul>
        </li>
        <li class="dropdown nav-top">
          <a href="#" class="dropdown-toggle on" data-toggle="dropdown">新闻动态</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'news:list' 'company' %}">公司要闻</a></li>
            <li><a href="{% url 'news:list' 'industry' %}">行业新闻</a></li>
            <li><a href="{% url 'news:list' 'notice' %}">通知公告</a></li>
          </ul>
        </li>
        <li class="dropdown nav-top">
          <a href="#" class="dropdown-toggle on" data-toggle="dropdown">产品中心</a>
          <ul class="dropdown-menu">
            <li v-for="product_type in menu['product_type_list']"><a :href="'/product/' + product_type" >[[product_type]]</a></li>
          </ul>
        </li>
        <li class="dropdown nav-top">
          <a href="#" class="dropdown-toggle on" data-toggle="dropdown">服务支持</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'service:download' %}">资料下载</a></li>
            <li><a href="{% url 'service:platform' %}">人脸识别开放平台</a></li>
          </ul>
        </li>
        <li class="dropdown nav-top">
          <a href="{% url 'science:index' %}">科研基地</a>
        </li>
        <li class="dropdown nav-top">
          <a href="#" class="dropdown-toggle on" data-toggle="dropdown">联系我们</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'contact:contact' %}">联系我们</a></li>
            <li><a href="{% url 'contact:recruit' %}">加入恒达</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="line"></div>
<script>
  var app = new Vue({
    delimiters: ["[[", "]]"],
    el: '#vue-app',
    data: {
      menu: {
        'product_type_list': ['-'],
      }
    },
    mounted() {
      axios
        .get("{% url 'product:type' %}")
        .then(response => {
          var data = response.data;
          console.log(data);
          for (var x in data) {
            console.log(x);
          }
          this.menu['product_type_list'] = data['product_type_list'];
        })
      $(function () {
        $(".dropdown").mouseover(function () {
          $(this).addClass("open")
        });
      });
      $(".dropdown").mouseleave(function () {
        $(this).removeClass("open");
      });
    }
  })
</script>

templates/f01_common/f04_footer.html
<!-- 页脚 -->
<div class="container web-footer">
  <!-- 站点地图 -->
  <div class="row" id="map-footer">
    <div class="col-md-2">
      <dl>
        <dt>公司简介</dt>
        <dd><a href="/aboutApp/survey/">公司概况</a></dd>
        <dd><a href="/aboutApp/honor/">荣誉资质</a></dd>
      </dl>
    </div>
    <div class="col-md-2">
      <dl>
        <dt>产品中心</dt>
        <dd><a href="/productsApp/products/robot/">家用机器人</a></dd>
        <dd><a href="/productsApp/products/monitor/">智能门锁</a></dd>
        <dd><a href="/productsApp/products/face/">人脸识别解决方案</a></dd>
      </dl>
    </div>
    <div class="col-md-2">
      <dl>
        <dt>服务支持</dt>
        <dd><a href="/serviceApp/download/">资料下载</a></dd>
        <dd><a href="/serviceApp/platform/">人脸识别开放平台</a></dd>
      </dl>
    </div>
    <div class="col-md-2">
      <dl>
        <dt>人才招聘</dt>
        <dd><a href="/contactApp/contact/">联系我们</a></dd>
        <dd><a href="/contactApp/recruit/">加入恒达</a></dd>
      </dl>
    </div>
    <div class="col-md-4" id="wx">
      <p>扫描二维码，关注我们</p>
      <img class="qrimg" src="/static/img/qr.png" alt="wx">
      <p>客服热线：<b style="font-size:20px">400 000 0000</b></p>
    </div>
  </div>
  <!-- 版权 -->
  <div class="row " id="patent-footer">
    <p class="foot_top"> © 2021 Python Web恒达科技官网开发示例 版权所有 | 粤ICP备19006378号</p>
  </div>
</div>