cms_api/api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    # path('api/graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
    # 忽略csrf_token验证
    path('api/graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    path('system/', include('f01_system.f01_urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home.index import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

zxkj/f01_index/urls.py
app_name = 'index'
urlpatterns = []

zxkj/f03_news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('<str:news_type>/', views.news, name='list'),
    path('detail/<int:id>/', views.details, name='detail'),
]

zxkj/f04_product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.list, name='list'),
    path('<str:product_type_name>/', views.list, name='list'),
    path('details/<int:id>/', views.details, name="details"),
    path('type', views.types_list, name="type"),
]

zxkj/f06_contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('recruit/', views.recruit, name='recruit'),
]

zxkj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .f01_index import views
from . import settings

urlpatterns = [

    path('', views.index, name='index'),
    path('profile/', include('zxkj.f02_profile.urls', namespace='profile')),   # 公司简介
    path('news/', include('zxkj.f03_news.urls', namespace='news')),   # 新闻动态
    path('product/', include('zxkj.f04_product.urls', namespace='product')),   # 产品中心
    path('science/', include('zxkj.f05_science.urls', namespace='science')),   # 科研基地
    path('contact/', include('zxkj.f06_contact.urls', namespace='contact')),   # 联系我们
    path('service/', include('zxkj.f08_service.urls', namespace='service')),   # 服务支持
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zxkj/f01_index/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class AD(models.Model):

    title = models.CharField(max_length=100, verbose_name='标题')
    photo = models.ImageField(upload_to='ad/', verbose_name="广告图片")
    url = models.CharField(max_length=500, verbose_name="URL链接")
    publish_date = models.DateTimeField(max_length=20, default=timezone.now, verbose_name="发布时间")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    sort = models.CharField(max_length=100, verbose_name='排序')
    state = models.CharField(max_length=100, default="1",verbose_name='状态') # 默认1 有效

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "广告"
        verbose_name_plural = "广告列表"
        ordering = ('-sort', '-publish_date')

zxkj/f01_index/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page


from django.db.models import Q
from .models import AD
from zxkj.f03_news.models import News
from zxkj.f04_product.models import Product
# from aboutApp.models import AboutUs



# Create your views here.
@cache_page(1)  # 单位：秒数，这里指缓存 15 分钟
def index(request):

    # 广告列表
    adList = AD.objects.filter(state='1').order_by('-sort','-publish_date')[:3]
    # 新闻展报
    newList = News.objects.filter(~Q(news_type='通知公告')).order_by('-publish_date')
    postList = set()
    postNum = 0
    for s in newList:
        if s.photo:
            postList.add(s)
            postNum += 1
        if postNum == 3:  # 只截取最近的3个展报
            break
    # 新闻列表
    if (len(newList) > 7):
        newList = newList[0:7]
    # 通知公告
    noteList = News.objects.all().filter(Q(news_type='通知公告')).order_by('-publish_date')
    if (len(noteList) > 7):
        noteList = noteList[0:7]
    # 产品中心
    productList = Product.objects.all().order_by('-views')
    if (len(productList) > 4):
        productList = productList[0:4]
    # 返回结果
    return render(request, 'f02_index/f01_index.html',{
        'active_menu': 'home',
        'adList': adList,
        'newList': newList,
        'postList': postList,
        'noteList': noteList,
        'productList': productList,
    })

templates/f02_index/f01_index.html
{% extends "../f01_common/f01_base.html" %}
{% load static %}
{% block title %}首页-恒达科技{% endblock %}
{% block content %}
<!-- AD -->
{% include "./f02_navbar_ad.html" %}
<!-- 主体内容 -->
<div class="container">
  <div class="row row-3">
    <!-- 公司概况模块 -->
    {% include "./f03_module_profile.html" %}
    <!-- 新闻动态模块 -->
    {% include "./f04_module_news.html" %}
  </div>
  <div class="row row-3">
    <!-- 通知公告模块 -->
    {% include "./f05_module_notice.html" %}
    <!-- 科研基地模块 -->
    {% include "./f06_module_science.html" %}
    <!-- 联系我们模块 -->
    {% include "./f07_module_contact.html" %}
  </div>
  <div class="row row-3">
    <!-- 产品中心模块 -->
    {% include "./f08_module_product.html" %}
  </div>
  <!-- 友情链接 -->
  <div class="row row-3"><div class="col-md-12"></div></div>
</div>
<script src="{% static 'js/jqthumb.min.js' %}"></script>
<script>
  //处理缩略图
  function DrawImage(hotimg) {
    $(hotimg).jqthumb({
      width: '100%', // 宽度
      height: '220px', // 高度
      zoom: '1', // 缩放比例
      method: 'auto' // 提交方法，用于不同的浏览器环境，默认为‘auto’
    });
  }
</script>
{% endblock %}

templates/f02_index/f02_navbar_ad.html
{% load static %}
<!-- 广告横幅 -->
<div id="ad" class="carousel slide" data-ride="carousel" data-interval="5000">
    <ol class="carousel-indicators">
        <li data-target="#ad" data-slide-to="0" class="active"></li>
        <li data-target="#ad" data-slide-to="1"></li>
        <li data-target="#ad" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        {% if adList|length > 0 %}
            {% for ad in adList %}
                <div class="item {% if forloop.first %} active {% endif %}" style = "min-height: 100px;max-height: 400px;">
                    <a href="{{ ad.url }}"><img src="{{ad.photo.url}}" alt="{{ad.title}}"></a>
                </div>
            {% endfor %}
        {% else %}
            <div class="item active">
                <img src="{% static 'img/banner1.jpg' %}" alt="广告横幅1">
            </div>
            <div class="item">
                <img src="{% static 'img/banner2.jpg' %}" alt="广告横幅2">
            </div>
            <div class="item">
                <img src="{% static 'img/banner3.jpg' %}" alt="广告横幅3">
            </div>
        {% endif %}
    </div>
    <a class="left carousel-control" href="#ad" data-slide="prev"><span
                                                class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#ad" data-slide="next"><span
                                                 class="glyphicon glyphicon-chevron-right"></span></a>
</div>

templates/f02_index/f03_module_profile.html
{% load static %}
<div class="col-md-4">
  <!-- 企业概况 -->
  <span class="part1">企业概况</span>
  <span class="part1 en">&nbsp;&nbsp;/ Company Profile</span>
  <div class="line1">
    <div class="line2 theme"></div>
  </div>
  <div style="margin-top:20px;">
    <img class="img-responsive" src="{% static 'img/aboutCompany.jpg' %}">
    <p class="text1">恒达科技有限企业，位于中国某高新技术产业开发区,以社会公共安全领域为主要应用方向，提供极速、准确和防伪装的人脸识别产品。</p>
  </div>
</div>

templates/f02_index/f04_module_news.html
{% load static %}
<div class="col-md-8">
  <!-- 新闻动态 -->
  <span class="part1">新闻动态</span>
  <span class="part1 en">
    &nbsp;&nbsp;/ News
  </span>
  <a class="btn btn-default btn-xs more-btn" href="{% url 'news:list' 'company' %}">
    +&nbsp;更多
  </a>
  <div class="line1">
    <div class="line2 theme"></div>
  </div>
  <div class="col-md-5">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators nav-point">
        {% for post in postList %}
        <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %} class="active"
          {% endif %}>
        </li>
        {% endfor %}
      </ol>
      <!-- 轮播（Carousel）项目 -->
      <div class="carousel-inner" style="margin-top:15px;">
        {% for post in postList %}
        <div {% if forloop.first %} class="item active" {% else %} class="item" {% endif %}
          style="background-size:cover;">
          <a href="{% url 'news:detail' post.id %}">
            <img src="{{ post.photo.url }}" class="img-responsive" onload="DrawImage(this)">
          </a>
          <div class="carousel-caption nav-title">{{ post.title }}</div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <ul class="list-unstyled list-new">
      {% for mynew in newList %}
      <li>
        <a href="{% url 'news:detail' mynew.id %}">
          {{ mynew.title|truncatechars:"15" }}</a>
        <span>【{{ mynew.publish_date|date:"Y-m-d" }}】</span>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

templates/f02_index/f05_module_notice.html
{% load static %}
<div class="col-md-4">
  <!-- 通知公告 -->
  <span class="part1">通知公告</span>
  <span class="part1 en">
    &nbsp;&nbsp;/ Public Release
  </span>
  <a class="btn btn-default btn-xs more-btn" href="{% url 'news:list' 'notice' %}">
    +&nbsp;更多
  </a>
  <div class="line1">
    <div class="line2 theme"></div>
  </div>
  <div>
    <img class="img-responsive" src="{% static 'img/note.jpg' %}">
    <ul class="list-unstyled list-new">
      {% for note in noteList %}
      <li>
        <a href="{% url 'news:detail' note.id %}">
          {{ note.title|truncatechars:"25" }}
        </a>
        <a href="{% url 'news:detail' note.id %}" class="public-detail">
          查看详情>>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

templates/f02_index/f06_module_science.html
{% load static %}
<div class="col-md-4">
  <!-- 科研基地 -->
  <span class="part1">科研基地</span>
  <span class="part1 en">
    &nbsp;&nbsp;/ Technology Center
  </span>
  <div class="line1">
    <div class="line2 theme"></div>
  </div>
  <div>
    <a href="{% url 'science:index' %}">
      <img class="img-responsive" src="{% static 'img/ky.jpg' %}">
    </a>
    <p class="text1">
      <font color="#d30a1c">恒达科技科研基地</font>
      恒达科研基地分为计算机视觉、 机器人和视觉深度学习三个事业部，共拥有高级研发人员近30名，
      以各领域高级工程师和知名院校博士为主体的多层次研发梯队。当前，科研基地优秀的技术团队
      已为恒达在人脸识别、物联网平台搭建、机器人导航等 领域打下了坚实基础
    </p>
  </div>
</div>

templates/f02_index/f07_module_contact.html
{% load static %}
<div class="col-md-4">
  <!-- 联系我们 -->
  <span class="part1">联系我们</span>
  <span class="part1 en">
    &nbsp;&nbsp;/ Contact us
  </span>
  <div class="line1">
    <div class="line2 theme"></div>
  </div>
  <div>
    <ul class="list-unstyled procurement-li">
      <li>业务质询一：111-XXXXXX</li>
      <li>业务质询二：222-XXXXXX</li>
      <li>咨询电话：0111-XXXXXX</li>
      <li>企业传真：0222-XXXXXX</li>
      <li>地址：某某某新区某某大道1号</li>
      <li>邮编：XXXXXX</li>
      <li>
        网址：<a href="http://python3web.com">http://python3web.com</a>
      </li>
    </ul>
    <div class="platform"><a href="{% url 'contact:contact' %}">详情</a></div>
  </div>
</div>

templates/f02_index/f08_module_product.html
{% load static %}
<!-- 产品中心 -->
<div class="col-md-12 col-pro">
  <span class="part1">产品中心</span>
  <span class="part1 en">
    &nbsp;&nbsp;/ Products
  </span>
  <a class="btn btn-default btn-xs more-btn" href="{% url 'product:list' %}">+&nbsp;更多</a>
  <div class="line1" style="margin-bottom:5px;">
    <div class="line2 theme"></div>
  </div>
  <div class="col-md-12 col-pro">
    <div id="Carousel" class="carousel slide" style="margin-bottom:30px">
      <ol class="carousel-indicators" style="display:none;">
        <li data-target="#Carousel" data-slide-to="0" class="active"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <div class="row">
            {% for product in productList %}
            <div class="col-md-3 pro-images">
              <a href="{% url 'product:details' product.id %}" class="thumbnail">
                <img src="{{ product.photo.url }}" alt="产品图片" class="img-responsive" onload="DrawImage(this)">
              </a>
              <div class="carousel-caption nav-title">{{ product.title }}</div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>