cms_api/api/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    # path('api/graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
    # 忽略csrf_token验证
    path('api/graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    path('system/', include('f01_system.f01_urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home.index import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

zxkj/f08_service/urls.py
from django.urls import path
from . import views,face_detect

app_name = 'service'
urlpatterns = [
    path('doc/download/', views.doc_list, name='download'),  # 资料下载页面
    path('doc/<int:id>/', views.doc, name='doc'),  # 资料下载
    path('platform/', views.platform, name='platform'),  # 人脸识别开放平台
    # path('platform/face_detect', face_detect.face_detect, name='face_detect'),  #人脸检测Demo
]

zxkj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .f01_index import views
from . import settings

urlpatterns = [

    path('', views.index, name='index'),
    path('profile/', include('zxkj.f02_profile.urls', namespace='profile')),   # 公司简介
    path('news/', include('zxkj.f03_news.urls', namespace='news')),   # 新闻动态
    path('product/', include('zxkj.f04_product.urls', namespace='product')),   # 产品中心
    path('science/', include('zxkj.f05_science.urls', namespace='science')),   # 科研基地
    path('contact/', include('zxkj.f06_contact.urls', namespace='contact')),   # 联系我们
    path('service/', include('zxkj.f08_service.urls', namespace='service')),   # 服务支持
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zxkj/f08_service/models.py
from django.db import models
from django.utils import timezone


class Doc(models.Model):
    """资料下载"""
    title = models.CharField(max_length=40, verbose_name="资料名称")
    file = models.FileField(upload_to='service/doc/', blank=True, verbose_name="文件资料")
    publish_date = models.DateTimeField(max_length=20, default=timezone.now, verbose_name="上传时间")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publish_date']
        verbose_name = "资料"
        verbose_name_plural = "资料"

zxkj/f08_service/views.py
from django.core.paginator import Paginator
from django.http import StreamingHttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.encoding import escape_uri_path
from .models import Doc

def doc_list(request):
    doc_list = Doc.objects.all().order_by('-publish_date')
    p = Paginator(doc_list, 5)
    if p.num_pages <= 1:
        page_data = ''
    else:
        page = int(request.GET.get('page', 1))
        doc_list = p.page(page)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        page_data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }
    return render(
        request, 'f08_service/f01_doc_list.html', {
            'active_menu': 'service',
            'doc_list': doc_list,
            'page_data': page_data,
        })


def doc(request, id):
    """下载文件"""
    doc = get_object_or_404(Doc, id=id)
    # 获取文件的名字
    file_name = str(doc.file).split('/')[-1]
    # 获取文件的路径
    file_path = '%s%s' % (os.getcwd(),doc.file.url)
    # 将下载文件分批次写入本地磁盘，先不将他们载入文件内存，读取文件，以512B为单位构建迭代器
    response = StreamingHttpResponse(read_file(file_path, 512))
    # 作为文件直接下载到本机，用户再用软件打开
    response['Content-Type'] = 'application/octet-stream'
    # 规定文件名的下载格式，在文件名为中文时，要加上escape_uri_path
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(escape_uri_path(file_name))
    return response


def platform(request):
    return render(request, 'f08_service/f02_plat_form.html', {
        'active_menu': 'service',
    })

def read_file(file_name, size):
    """分批读取文件"""
    with open(file_name, mode='rb') as fp:
        while True:
            c = fp.read(size)
            if c:
                yield c  # 生成器，相当于一个特殊的迭代器，当运行到这个语句的时候会保存当前的对象；下次再运行到这里的时候会接着上次的对象继续运行。
            else:
                break

templates/f08_service/f01_doc_list.html
{% extends "../f01_common/f01_base.html" %}
{% load static %}
{% block title %}资料下载{% endblock %}
{% block content %}
{# <link href="{% static 'css/news.css' %}" rel="stylesheet">#}
<!-- 广告横幅 -->
<div class="container-fluid">
  <div class="row">
    <img class="img-responsive model-img" src="{% static 'img/service.jpg' %}">
  </div>
</div>
<!-- 主体内容 -->
<div class="container">
  <div class="row row-3">
    <!-- 侧边导航栏 -->
    <div class="col-md-3">
      <div class="model-title">
        服务支持
      </div>
      <div class="model-list">
        <ul class="list-group">
          <li class="list-group-item" id='download'>
            <a href="{% url 'service:download' %}">资料下载</a>
          </li>
          <li class="list-group-item" id='platform'>
            <a href="{% url 'service:platform' %}">人脸识别</a>
          </li>
        </ul>
      </div>
    </div>
    <!-- 说明文字和图片 -->
    <div class="col-md-9">
      <div class="model-details-title">资料列表</div>
      <div class="model-details">
        {% for doc in doc_list %}
        <div class="news-model">
          <img src="{% static 'img/newsicon.gif' %}">
          <a href="{% url 'service:doc' doc.id %}"><b>{{ doc.title }}</b></a>
          <span>【{{ doc.publish_date|date:"Y-m-d" }}】</span>
        </div>
        {% endfor %}

        {% if page_data %}
        <div class="paging">
          <ul id="pages" class="pagination">
            {% if page_data.first %}
            <li><a href="?page=1">1</a></li>
            {% endif %}
            {% if page_data.left %}
            {% if page_data.left_has_more %}
            <li><span>...</span></li>
            {% endif %}
            {% for i in page_data.left %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% endif %}
            <li class="active"><a href="?page={{ page_data.page }}">
                {{ page_data.page }}</a></li>
            {% if page_data.right %}
            {% for i in page_data.right %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if page_data.right_has_more %}
            <li><span>...</span></li>
            {% endif %}
            {% endif %}
            {% if page_data.last %}
            <li><a href="?page={{ page_data.total_pages }}">
                {{ page_data.total_pages }}</a></li>
            {% endif %}
          </ul>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/f08_service/f02_plat_form.html
{% extends "../f01_common/f01_base.html" %}
{% load static %}
{% block title %}人脸识别{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/codemirror.css' %}">
<script src="{% static 'js/codemirror.js' %}"></script>
<script src="{% static 'js/python.js' %}"></script>
<style type="text/css">
  .CodeMirror {
    border-top: 1px solid black;
    border-bottom: 1px solid black;
  }
</style>
<!-- 广告横幅 -->
<div class="container-fluid">
  <div class="row">
    <img class="img-responsive model-img" src="{% static 'img/service.jpg' %}">
  </div>
</div>
<!-- 主体内容 -->
<div class="container">
  <div class="row row-3">
    <!-- 侧边导航栏 -->
    <div class="col-md-3">
      <div class="model-title">
        服务支持
      </div>
      <div class="model-list">
        <ul class="list-group">
          <li class="list-group-item" id='download'>
            <a href="{% url 'service:download' %}">资料下载</a>
          </li>
          <li class="list-group-item" id='platform'>
            <a href="{% url 'service:platform' %}">人脸识别</a>
          </li>
        </ul>
      </div>
    </div>
    <!-- 说明文字和图片 -->
    <div class="col-md-9">
      <div class="model-details-title">人脸识别接口文档</div>
      <div class="model-details">
        <h3>一. 体验产品</h3>
        </br>
        <!-- 按钮触发模态框 -->
        <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          人脸检测
        </button>
        <!-- 模态框（Modal） -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
          aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                  &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">
                  在线人脸检测
                </h4>
              </div>
              <div class="modal-body">
                <img id="photoIn" src="{% static 'img/sample.png' %}" class="img-responsive" style="max-width:250px">
                <input type="file" id="photo" name="photo" />
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                </button>
                <button type="button" id="compute" class="btn btn-primary">
                  开始检测
                </button>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal -->
        </div>
        <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
        <script>
          $(function () {
            $('#photo').on('change', function () {
              var r = new FileReader();
              f = document.getElementById('photo').files[0];
              r.readAsDataURL(f);
              r.onload = function (e) {
                document.getElementById('photoIn').src = this.result;
              };
            });
          });
        </script>
        <script>
          $('#compute').click(function () {
            formdata = new FormData();
            var file = $("#photo")[0].files[0];
            formdata.append("image", file);
            $.ajax({
              url: "/service/face_detect", // 调用Django服务器计算函数
              type: 'POST', // 请求类型
              data: formdata,
              dataType: 'json', // 期望获得的响应类型为json
              processData: false,
              contentType: false,
              success: ShowResult // 在请求成功之后调用该回调函数输出结果
            })
          })
        </script>
        <script>
          function ShowResult(data) {
            var v = data['img64'];
            document.getElementById('photoIn').src = "data:image/jpeg;base64, " + v;
          }
        </script>
        <h3>二. API接口说明</h3>
        </br>
        <h4><strong>基本信息：</strong></h4>
        <p>
          请求类型：HTTP/HTTPS。请求方式：POST
        </p>
        <p>
          接口地址：http://myhengda.cn/serviceApp/facedetect/
        </p>
        </br>
        <h4><strong>接口描述：</strong></h4>
        <p>
          人脸检测，此接口多用于调用人脸识别、人脸比对的接口之前，用于从图像数据中检测出人脸区域，并以
          矩形框形式返回人脸检测结果。目前该接口仅供测试使用，调用该接口暂时不限制调用次数。
        </p>

        </br>
        <h4><strong>本地调用示例：</strong></h4>

        <div><textarea id="code" name="code">
          import cv2, requests
          # web地址(http://localhost:8000)+访问接口（facedetect）
          url = "http://localhost:8000/serviceApp/facedetect/"

          # 上传图像并检测
          tracker = None
          imgPath = "face.jpg"  #图像路径
          files = {
              "image": ("filename2", open(imgPath, "rb"), "image/jpeg"),
          }

          req = requests.post(url, data=tracker, files=files).json()
          print("获取信息: {}".format(req))

          # 将检测结果框显示在图像上
          img = cv2.imread(imgPath)
          for (w, x, y, z) in req["faces"]:
              cv2.rectangle(img, (w, x), (y, z), (0, 255, 0), 2)

          cv2.imshow("face detection", img)
          cv2.waitKey(0)
        </textarea></div>
        </br>
        <h4><strong>调用结果：</strong></h4>
        <img class="img-responsive" style="max-width:200px;" src="{% static 'img/facedetect.png' %}">

      </div>
    </div>
  </div>
</div>

<script>
  var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
    mode: {
      name: "python",
      version: 3,
      singleLineStringErrors: false
    },
    lineNumbers: true,
    indentUnit: 4,
    tabMode: "shift",
    matchBrackets: true
  });
</script>
{% endblock %}